print("Hallo ik ben Kiet.?")
naam = input("Wat is jou naam?")
print("Hallo " + naam + " Leuk om jou te ontmoeten")
print("Ik ben 16 jaar oud")
age = input("Hoe oud ben jij?")
print("Aha, je bent dus " + age + " jaar oud, leuk zeg!")
woonplaats = input("Waar woon je?")
print("Wat leuk dat je in" + woonplaats + "woont")
print("Hallo " + naam + " dus je bent " + age + " en woont in " + woonplaats + " wat leuk!")